config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :spin_vfs_storage_mappings

  resources :spin_vfs_tree_mappings

  resources :spin_virtual_file_systems

  resources :user_interface_managers

  resources :spin_user_attributes

  resources :secrfet_files_login

  resources :spin_objects

  resources :spin_storages

  resources :spin_domains

  resources :spin_sessions

  resources :spin_group_members

  resources :spin_users

  resources :spin_groups

  resources :target_folder_data

  resources :sender_data

  resources :search_option_data

  resources :search_condition_data

  resources :recycler_data

  resources :operator_data

  resources :member_data

  resources :group_data

  resources :folder_data

  resources :file_data

  resources :domain_data

  resources :secret_files_sessions

  get 'hello_world', to: 'hello_world#index'

  get 'secret_files_login/login.tdx'  => 'secret_files_login#proc_login'
  match 'secret_files/login.tdx'  => 'secret_files_login#proc_login', :via => [:get, :post]
  get 'secret_files_login/activation.php'  => 'secret_files_login#proc_activation'
  get 'secret_files_login/auth.html'  => 'secret_files_login#proc_secret_files_login_view'
  get 'secret_files_login'  => 'secret_files_login#proc_secret_files_login_view'
  match 'secret_files_login/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  match 'secret_files/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  get 'secret_files/uploader/upload_proc' => 'uploader#upload_proc'
  get 'secret_files/downloader/download_proc' => 'downloader#download_proc'
  get 'secret_files/secret_files/spin_api_request' => 'fsmanager#spin_api_request_proc'
  get 'secret_files/secret_files/multipart_form' => 'uploader#filemanager_upload_request'
  post 'secret_files_login/login.tdx'  => 'secret_files_login#proc_login'
  post 'secret_files_login/activation.php'  => 'secret_files_login#proc_activation'
  post 'secret_files_login/auth.html'  => 'secret_files_login#proc_secret_files_login_view'
  post 'secret_files_login'  => 'secret_files_login#proc_secret_files_login_view'
  match 'secret_files_login/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  match 'secret_files/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  post 'secret_files/uploader/upload_proc' => 'uploader#upload_proc'
  post 'secret_files/downloader/download_proc' => 'downloader#download_proc'
  post 'secret_files/secret_files/spin_api_request' => 'fsmanager#spin_api_request_proc'
  post 'secret_files/secret_files/multipart_form' => 'uploader#filemanager_upload_request'
  get 'secret_files_ipad/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_ipad/tdx/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_ipad/tdx/updatedata.tdx' => 'secret_files#php'
  get 'secret_files_ipad'  => 'secret_files_login#proc_secret_files_ipad_login_view'
  get 'secret_files_ipad/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_ipad/tdx/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_ipad/index.html' => 'secret_files#proc_login_view'
  get 'secret_files_iphone/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_iphone/tdx/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_iphone/tdx/updatedata.tdx' => 'secret_files#php'
  get 'secret_files_iphone'  => 'secret_files_login#proc_secret_files_ipad_login_view'
  get 'secret_files_iphone/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_iphone/tdx/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_iphone/index.html' => 'secret_files#proc_login_view'
  get 'secret_files/spin_api_request' => 'spin_api#request_broker'
  post 'secret_files/spin_api_request' => 'spin_api#request_broker'
  get 'm2a/index.tdx' => 'spin_m2a#proc_login_view'
  get 'm2a/index.html' => 'spin_m2a#proc_login_view'
  get 'secret_files/spin/domainsA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/domainsB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersAT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersBT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersATFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersBTFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/file_listA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/file_listB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/file_listS.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/recycler.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/search_option.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/search_conditions.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_tree.sfl' => 'filer_display#proc_display_view'
  get 'secret_files/spin/group_list_all.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_folder.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_file.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_created.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/member_list_mygroup.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/mail_senders.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/working_files.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/active_operator.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_created.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/user_list.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/select_list.sfl' => 'filer_display#proc_display_view'

  get 'secret_files/spin/clipboards.sfl' => 'filer_display#proc_display_view' # => domain name and attributes

  get 'secret_files/spin/ArchivedData.sfl' => 'filer_display#proc_display_view' #アーカイブ解除
  get 'secret_files/spin/SyncedData.sfl' => 'filer_display#proc_display_view' #同期解除
  get 'secret_files/spin/dlfolders.sfl' => 'filer_display#proc_display_view' #ダウンロード
  get 'secret_files/spin/dlfiles.sfl' => 'filer_display#proc_display_view' #ダウンロード

  post 'secret_files/spin/domainsA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/domainsB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersAT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersBT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersATFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersBTFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/file_listA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/file_listB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/file_listS.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/recycler.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/search_option.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/search_conditions.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_tree.sfl' => 'filer_display#proc_display_view'
  post 'secret_files/spin/group_list_all.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_folder.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_file.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_created.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/member_list_mygroup.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/mail_senders.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/working_files.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/active_operator.sfl' => 'filer_display#proc_display_view' # => domain name and attributes

app/controllers/file_data_controller.rb
class FileDataController < ApplicationController
  # GET /file_data
  # GET /file_data.json
  def index
    @file_data = FileDatum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @file_data }
    end
  end

  # GET /file_data/1
  # GET /file_data/1.json
  def show
    @file_datum = FileDatum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @file_datum }
    end
  end

  # GET /file_data/new
  # GET /file_data/new.json
  def new
    @file_datum = FileDatum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @file_datum }
    end
  end

  # GET /file_data/1/edit
  def edit
    @file_datum = FileDatum.find(params[:id])
  end

  # POST /file_data
  # POST /file_data.json
  def create
    @file_datum = FileDatum.new(params[:file_datum])

    respond_to do |format|
      if @file_datum.save
        format.html { redirect_to @file_datum, :notice => 'File datum was successfully created.' }
        format.json { render :json => @file_datum, :status => :created, :location => @file_datum }
      else
        format.html { render :action => "new" }
        format.json { render :json => @file_datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /file_data/1
  # PUT /file_data/1.json
  def update
    @file_datum = FileDatum.find(params[:id])

    respond_to do |format|
      if @file_datum.update_attributes(params[:file_datum])
        format.html { redirect_to @file_datum, :notice => 'File datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @file_datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /file_data/1
  # DELETE /file_data/1.json
  def destroy
    @file_datum = FileDatum.find(params[:id])
    @file_datum.destroy

    respond_to do |format|
      format.html { redirect_to file_data_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/file_data_helper.rb
module FileDataHelper
end

app/views/file_data/_form.html.erb
<%= form_for(@file_datum) do |f| %>
  <% if @file_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_datum.errors.count, "error") %> prohibited this file_datum from being saved:</h2>

      <ul>
      <% @file_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :session_id %><br />
    <%= f.text_field :session_id %>
  </div>
  <div class="field">
    <%= f.label :hash_key %><br />
    <%= f.text_field :hash_key %>
  </div>
  <div class="field">
    <%= f.label :cont_location %><br />
    <%= f.text_field :cont_location %>
  </div>
  <div class="field">
    <%= f.label :file_name %><br />
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :file_type %><br />
    <%= f.text_field :file_type %>
  </div>
  <div class="field">
    <%= f.label :file_size %><br />
    <%= f.number_field :file_size %>
  </div>
  <div class="field">
    <%= f.label :file_version %><br />
    <%= f.number_field :file_version %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :thumbnail_image %><br />
    <%= f.text_field :thumbnail_image %>
  </div>
  <div class="field">
    <%= f.label :created_date %><br />
    <%= f.date_select :created_date %>
  </div>
  <div class="field">
    <%= f.label :creator %><br />
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :modified_date %><br />
    <%= f.date_select :modified_date %>
  </div>
  <div class="field">
    <%= f.label :modifier %><br />
    <%= f.text_field :modifier %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :ownership %><br />
    <%= f.text_field :ownership %>
  </div>
  <div class="field">
    <%= f.label :control_right %><br />
    <%= f.text_field :control_right %>
  </div>
  <div class="field">
    <%= f.label :lock %><br />
    <%= f.text_field :lock %>
  </div>
  <div class="field">
    <%= f.label :id_lc_by %><br />
    <%= f.text_field :id_lc_by %>
  </div>
  <div class="field">
    <%= f.label :name_lc_by %><br />
    <%= f.text_field :name_lc_by %>
  </div>
  <div class="field">
    <%= f.label :dirty %><br />
    <%= f.text_field :dirty %>
  </div>
  <div class="field">
    <%= f.label :keyword %><br />
    <%= f.text_field :keyword %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :file_exact_size %><br />
    <%= f.number_field :file_exact_size %>
  </div>
  <div class="field">
    <%= f.label :icon_image %><br />
    <%= f.text_field :icon_image %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :frame_size %><br />
    <%= f.text_field :frame_size %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :producer %><br />
    <%= f.text_field :producer %>
  </div>
  <div class="field">
    <%= f.label :produced_date %><br />
    <%= f.date_select :produced_date %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :client %><br />
    <%= f.text_field :client %>
  </div>
  <div class="field">
    <%= f.label :copyright %><br />
    <%= f.text_field :copyright %>
  </div>
  <div class="field">
    <%= f.label :portrait_right %><br />
    <%= f.text_field :portrait_right %>
  </div>
  <div class="field">
    <%= f.label :access_group %><br />
    <%= f.text_field :access_group %>
  </div>
  <div class="field">
    <%= f.label :file_readable_status %><br />
    <%= f.text_field :file_readable_status %>
  </div>
  <div class="field">
    <%= f.label :file_writable_status %><br />
    <%= f.text_field :file_writable_status %>
  </div>
  <div class="field">
    <%= f.label :open_status %><br />
    <%= f.text_field :open_status %>
  </div>
  <div class="field">
    <%= f.label :folder_hash_key %><br />
    <%= f.text_field :folder_hash_key %>
  </div>
  <div class="field">
    <%= f.label :folder_readable_status %><br />
    <%= f.text_field :folder_readable_status %>
  </div>
  <div class="field">
    <%= f.label :folder_writable_status %><br />
    <%= f.text_field :folder_writable_status %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_field :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_data/edit.html.erb
<h1>Editing file_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_datum %> |
<%= link_to 'Back', file_data_path %>

app/views/file_data/index.html.erb
<h1>Listing file_data</h1>

<table>
  <tr>
    <th>Session</th>
    <th>Hash key</th>
    <th>Cont location</th>
    <th>File name</th>
    <th>File type</th>
    <th>File size</th>
    <th>File version</th>
    <th>Url</th>
    <th>Thumbnail image</th>
    <th>Created date</th>
    <th>Creator</th>
    <th>Modified date</th>
    <th>Modifier</th>
    <th>Owner</th>
    <th>Ownership</th>
    <th>Control right</th>
    <th>Lock</th>
    <th>Id lc by</th>
    <th>Name lc by</th>
    <th>Dirty</th>
    <th>Keyword</th>
    <th>Description</th>
    <th>File exact size</th>
    <th>Icon image</th>
    <th>Title</th>
    <th>Subtitle</th>
    <th>Frame size</th>
    <th>Duration</th>
    <th>Producer</th>
    <th>Produced date</th>
    <th>Location</th>
    <th>Client</th>
    <th>Copyright</th>
    <th>Portrait right</th>
    <th>Access group</th>
    <th>File readable status</th>
    <th>File writable status</th>
    <th>Open status</th>
    <th>Folder hash key</th>
    <th>Folder readable status</th>
    <th>Folder writable status</th>
    <th>Details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @file_data.each do |file_datum| %>
  <tr>
    <td><%= file_datum.session_id %></td>
    <td><%= file_datum.hash_key %></td>
    <td><%= file_datum.cont_location %></td>
    <td><%= file_datum.file_name %></td>
    <td><%= file_datum.file_type %></td>
    <td><%= file_datum.file_size %></td>
    <td><%= file_datum.file_version %></td>
    <td><%= file_datum.url %></td>
    <td><%= file_datum.thumbnail_image %></td>
    <td><%= file_datum.created_date %></td>
    <td><%= file_datum.creator %></td>
    <td><%= file_datum.modified_date %></td>
    <td><%= file_datum.modifier %></td>
    <td><%= file_datum.owner %></td>
    <td><%= file_datum.ownership %></td>
    <td><%= file_datum.control_right %></td>
    <td><%= file_datum.lock %></td>
    <td><%= file_datum.id_lc_by %></td>
    <td><%= file_datum.name_lc_by %></td>
    <td><%= file_datum.dirty %></td>
    <td><%= file_datum.keyword %></td>
    <td><%= file_datum.description %></td>
    <td><%= file_datum.file_exact_size %></td>
    <td><%= file_datum.icon_image %></td>
    <td><%= file_datum.title %></td>
    <td><%= file_datum.subtitle %></td>
    <td><%= file_datum.frame_size %></td>
    <td><%= file_datum.duration %></td>
    <td><%= file_datum.producer %></td>
    <td><%= file_datum.produced_date %></td>
    <td><%= file_datum.location %></td>
    <td><%= file_datum.client %></td>
    <td><%= file_datum.copyright %></td>
    <td><%= file_datum.portrait_right %></td>
    <td><%= file_datum.access_group %></td>
    <td><%= file_datum.file_readable_status %></td>
    <td><%= file_datum.file_writable_status %></td>
    <td><%= file_datum.open_status %></td>
    <td><%= file_datum.folder_hash_key %></td>
    <td><%= file_datum.folder_readable_status %></td>
    <td><%= file_datum.folder_writable_status %></td>
    <td><%= file_datum.details %></td>
    <td><%= link_to 'Show', file_datum %></td>
    <td><%= link_to 'Edit', edit_file_datum_path(file_datum) %></td>
    <td><%= link_to 'Destroy', file_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New File datum', new_file_datum_path %>

app/views/file_data/new.html.erb
<h1>New file_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', file_data_path %>

app/views/file_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Session:</b>
  <%= @file_datum.session_id %>
</p>

<p>
  <b>Hash key:</b>
  <%= @file_datum.hash_key %>
</p>

<p>
  <b>Cont location:</b>
  <%= @file_datum.cont_location %>
</p>

<p>
  <b>File name:</b>
  <%= @file_datum.file_name %>
</p>

<p>
  <b>File type:</b>
  <%= @file_datum.file_type %>
</p>

<p>
  <b>File size:</b>
  <%= @file_datum.file_size %>
</p>

<p>
  <b>File version:</b>
  <%= @file_datum.file_version %>
</p>

<p>
  <b>Url:</b>
  <%= @file_datum.url %>
</p>

<p>
  <b>Thumbnail image:</b>
  <%= @file_datum.thumbnail_image %>
</p>

<p>
  <b>Created date:</b>
  <%= @file_datum.created_date %>
</p>

<p>
  <b>Creator:</b>
  <%= @file_datum.creator %>
</p>

<p>
  <b>Modified date:</b>
  <%= @file_datum.modified_date %>
</p>

<p>
  <b>Modifier:</b>
  <%= @file_datum.modifier %>
</p>

<p>
  <b>Owner:</b>
  <%= @file_datum.owner %>
</p>

<p>
  <b>Ownership:</b>
  <%= @file_datum.ownership %>
</p>

<p>
  <b>Control right:</b>
  <%= @file_datum.control_right %>
</p>

<p>
  <b>Lock:</b>
  <%= @file_datum.lock %>
</p>

<p>
  <b>Id lc by:</b>
  <%= @file_datum.id_lc_by %>
</p>

<p>
  <b>Name lc by:</b>
  <%= @file_datum.name_lc_by %>
</p>

<p>
  <b>Dirty:</b>
  <%= @file_datum.dirty %>
</p>

<p>
  <b>Keyword:</b>
  <%= @file_datum.keyword %>
</p>

<p>
  <b>Description:</b>
  <%= @file_datum.description %>
</p>

<p>
  <b>File exact size:</b>
  <%= @file_datum.file_exact_size %>
</p>

<p>
  <b>Icon image:</b>
  <%= @file_datum.icon_image %>
</p>

<p>
  <b>Title:</b>
  <%= @file_datum.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @file_datum.subtitle %>
</p>

<p>
  <b>Frame size:</b>
  <%= @file_datum.frame_size %>
</p>

<p>
  <b>Duration:</b>
  <%= @file_datum.duration %>
</p>

<p>
  <b>Producer:</b>
  <%= @file_datum.producer %>
</p>

<p>
  <b>Produced date:</b>
  <%= @file_datum.produced_date %>
</p>

<p>
  <b>Location:</b>
  <%= @file_datum.location %>
</p>

<p>
  <b>Client:</b>
  <%= @file_datum.client %>
</p>

<p>
  <b>Copyright:</b>
  <%= @file_datum.copyright %>
</p>

<p>
  <b>Portrait right:</b>
  <%= @file_datum.portrait_right %>
</p>

<p>
  <b>Access group:</b>
  <%= @file_datum.access_group %>
</p>

<p>
  <b>File readable status:</b>
  <%= @file_datum.file_readable_status %>
</p>

<p>
  <b>File writable status:</b>
  <%= @file_datum.file_writable_status %>
</p>

<p>
  <b>Open status:</b>
  <%= @file_datum.open_status %>
</p>

<p>
  <b>Folder hash key:</b>
  <%= @file_datum.folder_hash_key %>
</p>

<p>
  <b>Folder readable status:</b>
  <%= @file_datum.folder_readable_status %>
</p>

<p>
  <b>Folder writable status:</b>
  <%= @file_datum.folder_writable_status %>
</p>

<p>
  <b>Details:</b>
  <%= @file_datum.details %>
</p>


<%= link_to 'Edit', edit_file_datum_path(@file_datum) %> |
<%= link_to 'Back', file_data_path %>