config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :spin_vfs_storage_mappings

  resources :spin_vfs_tree_mappings

  resources :spin_virtual_file_systems

  resources :user_interface_managers

  resources :spin_user_attributes

  resources :secrfet_files_login

  resources :spin_objects

  resources :spin_storages

  resources :spin_domains

  resources :spin_sessions

  resources :spin_group_members

  resources :spin_users

  resources :spin_groups

  resources :target_folder_data

  resources :sender_data

  resources :search_option_data

  resources :search_condition_data

  resources :recycler_data

  resources :operator_data

  resources :member_data

  resources :group_data

  resources :folder_data

  resources :file_data

  resources :domain_data

  resources :secret_files_sessions

  get 'hello_world', to: 'hello_world#index'

  get 'secret_files_login/login.tdx'  => 'secret_files_login#proc_login'
  match 'secret_files/login.tdx'  => 'secret_files_login#proc_login', :via => [:get, :post]
  get 'secret_files_login/activation.php'  => 'secret_files_login#proc_activation'
  get 'secret_files_login/auth.html'  => 'secret_files_login#proc_secret_files_login_view'
  get 'secret_files_login'  => 'secret_files_login#proc_secret_files_login_view'
  match 'secret_files_login/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  match 'secret_files/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  get 'secret_files/uploader/upload_proc' => 'uploader#upload_proc'
  get 'secret_files/downloader/download_proc' => 'downloader#download_proc'
  get 'secret_files/secret_files/spin_api_request' => 'fsmanager#spin_api_request_proc'
  get 'secret_files/secret_files/multipart_form' => 'uploader#filemanager_upload_request'
  post 'secret_files_login/login.tdx'  => 'secret_files_login#proc_login'
  post 'secret_files_login/activation.php'  => 'secret_files_login#proc_activation'
  post 'secret_files_login/auth.html'  => 'secret_files_login#proc_secret_files_login_view'
  post 'secret_files_login'  => 'secret_files_login#proc_secret_files_login_view'
  match 'secret_files_login/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  match 'secret_files/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  post 'secret_files/uploader/upload_proc' => 'uploader#upload_proc'
  post 'secret_files/downloader/download_proc' => 'downloader#download_proc'
  post 'secret_files/secret_files/spin_api_request' => 'fsmanager#spin_api_request_proc'
  post 'secret_files/secret_files/multipart_form' => 'uploader#filemanager_upload_request'
  get 'secret_files_ipad/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_ipad/tdx/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_ipad/tdx/updatedata.tdx' => 'secret_files#php'
  get 'secret_files_ipad'  => 'secret_files_login#proc_secret_files_ipad_login_view'
  get 'secret_files_ipad/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_ipad/tdx/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_ipad/index.html' => 'secret_files#proc_login_view'
  get 'secret_files_iphone/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_iphone/tdx/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_iphone/tdx/updatedata.tdx' => 'secret_files#php'
  get 'secret_files_iphone'  => 'secret_files_login#proc_secret_files_ipad_login_view'
  get 'secret_files_iphone/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_iphone/tdx/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_iphone/index.html' => 'secret_files#proc_login_view'
  get 'secret_files/spin_api_request' => 'spin_api#request_broker'
  post 'secret_files/spin_api_request' => 'spin_api#request_broker'
  get 'm2a/index.tdx' => 'spin_m2a#proc_login_view'
  get 'm2a/index.html' => 'spin_m2a#proc_login_view'
  get 'secret_files/spin/domainsA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/domainsB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersAT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersBT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersATFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersBTFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/file_listA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/file_listB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/file_listS.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/recycler.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/search_option.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/search_conditions.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_tree.sfl' => 'filer_display#proc_display_view'
  get 'secret_files/spin/group_list_all.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_folder.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_file.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_created.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/member_list_mygroup.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/mail_senders.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/working_files.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/active_operator.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_created.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/user_list.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/select_list.sfl' => 'filer_display#proc_display_view'

  get 'secret_files/spin/clipboards.sfl' => 'filer_display#proc_display_view' # => domain name and attributes

  get 'secret_files/spin/ArchivedData.sfl' => 'filer_display#proc_display_view' #アーカイブ解除
  get 'secret_files/spin/SyncedData.sfl' => 'filer_display#proc_display_view' #同期解除
  get 'secret_files/spin/dlfolders.sfl' => 'filer_display#proc_display_view' #ダウンロード
  get 'secret_files/spin/dlfiles.sfl' => 'filer_display#proc_display_view' #ダウンロード

  post 'secret_files/spin/domainsA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/domainsB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersAT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersBT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersATFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersBTFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/file_listA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/file_listB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/file_listS.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/recycler.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/search_option.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/search_conditions.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_tree.sfl' => 'filer_display#proc_display_view'
  post 'secret_files/spin/group_list_all.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_folder.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_file.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_created.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/member_list_mygroup.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/mail_senders.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/working_files.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/active_operator.sfl' => 'filer_display#proc_display_view' # => domain name and attributes

app/models/spin_object.rb
# coding: utf-8
require 'const/vfs_const'
require 'const/acl_const'

class SpinObject < ActiveRecord::Base
  include Vfs
  
  attr_accessor :date_created, :date_modified, :node_type, :node_version, :node_x_coord, :node_x_pr_coord, :node_y_coord, :object_attributes, :object_name, :src_attributes, :src_platform
  
  def self.get_object_name_by_key node_key
    obj = self.find_by_node_hashkey node_key
    if obj
      return obj[:object_name]
    else
      return nil
    end
  end # => end of get_object_name_by_key
  
  def self.get_object_name node_key
    obj = self.find_by_node_hashkey node_key
    return obj[:object_name]
  end # => end of get_object_name_by_key
  
end

app/controllers/spin_objects_controller.rb
class SpinObjectsController < ApplicationController
  # GET /spin_objects
  # GET /spin_objects.json
  def index
    @spin_objects = SpinObject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @spin_objects }
    end
  end

  # GET /spin_objects/1
  # GET /spin_objects/1.json
  def show
    @spin_object = SpinObject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @spin_object }
    end
  end

  # GET /spin_objects/new
  # GET /spin_objects/new.json
  def new
    @spin_object = SpinObject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @spin_object }
    end
  end

  # GET /spin_objects/1/edit
  def edit
    @spin_object = SpinObject.find(params[:id])
  end

  # POST /spin_objects
  # POST /spin_objects.json
  def create
    @spin_object = SpinObject.new(params[:spin_object])

    respond_to do |format|
      if @spin_object.save
        format.html { redirect_to @spin_object, :notice => 'Spin object was successfully created.' }
        format.json { render :json => @spin_object, :status => :created, :location => @spin_object }
      else
        format.html { render :action => "new" }
        format.json { render :json => @spin_object.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /spin_objects/1
  # PUT /spin_objects/1.json
  def update
    @spin_object = SpinObject.find(params[:id])

    respond_to do |format|
      if @spin_object.update_attributes(params[:spin_object])
        format.html { redirect_to @spin_object, :notice => 'Spin object was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @spin_object.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /spin_objects/1
  # DELETE /spin_objects/1.json
  def destroy
    @spin_object = SpinObject.find(params[:id])
    @spin_object.destroy

    respond_to do |format|
      format.html { redirect_to spin_objects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/spin_objects_helper.rb
module SpinObjectsHelper
end

app/views/spin_objects/_form.html.erb
<%= form_for(@spin_object) do |f| %>
  <% if @spin_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spin_object.errors.count, "error") %> prohibited this spin_object from being saved:</h2>

      <ul>
      <% @spin_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :node_x_coord %><br />
    <%= f.number_field :node_x_coord %>
  </div>
  <div class="field">
    <%= f.label :node_y_coord %><br />
    <%= f.number_field :node_y_coord %>
  </div>
  <div class="field">
    <%= f.label :node_x_pr_coord %><br />
    <%= f.number_field :node_x_pr_coord %>
  </div>
  <div class="field">
    <%= f.label :node_type %><br />
    <%= f.number_field :node_type %>
  </div>
  <div class="field">
    <%= f.label :node_version %><br />
    <%= f.number_field :node_version %>
  </div>
  <div class="field">
    <%= f.label :object_name %><br />
    <%= f.text_field :object_name %>
  </div>
  <div class="field">
    <%= f.label :object_attributes %><br />
    <%= f.text_area :object_attributes %>
  </div>
  <div class="field">
    <%= f.label :src_platform %><br />
    <%= f.text_field :src_platform %>
  </div>
  <div class="field">
    <%= f.label :src_attributes %><br />
    <%= f.text_area :src_attributes %>
  </div>
  <div class="field">
    <%= f.label :date_created %><br />
    <%= f.date_select :date_created %>
  </div>
  <div class="field">
    <%= f.label :date_modified %><br />
    <%= f.date_select :date_modified %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spin_objects/edit.html.erb
<h1>Editing spin_object</h1>

<%= render 'form' %>

<%= link_to 'Show', @spin_object %> |
<%= link_to 'Back', spin_objects_path %>

app/views/spin_objects/index.html.erb
<h1>Listing spin_objects</h1>

<table>
  <tr>
    <th>Node x coord</th>
    <th>Node y coord</th>
    <th>Node x pr coord</th>
    <th>Node type</th>
    <th>Node version</th>
    <th>Object name</th>
    <th>Object attributes</th>
    <th>Src platform</th>
    <th>Src attributes</th>
    <th>Date created</th>
    <th>Date modified</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spin_objects.each do |spin_object| %>
  <tr>
    <td><%= spin_object.node_x_coord %></td>
    <td><%= spin_object.node_y_coord %></td>
    <td><%= spin_object.node_x_pr_coord %></td>
    <td><%= spin_object.node_type %></td>
    <td><%= spin_object.node_version %></td>
    <td><%= spin_object.object_name %></td>
    <td><%= spin_object.object_attributes %></td>
    <td><%= spin_object.src_platform %></td>
    <td><%= spin_object.src_attributes %></td>
    <td><%= spin_object.date_created %></td>
    <td><%= spin_object.date_modified %></td>
    <td><%= link_to 'Show', spin_object %></td>
    <td><%= link_to 'Edit', edit_spin_object_path(spin_object) %></td>
    <td><%= link_to 'Destroy', spin_object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spin object', new_spin_object_path %>

app/views/spin_objects/new.html.erb
<h1>New spin_object</h1>

<%= render 'form' %>

<%= link_to 'Back', spin_objects_path %>

app/views/spin_objects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Node x coord:</b>
  <%= @spin_object.node_x_coord %>
</p>

<p>
  <b>Node y coord:</b>
  <%= @spin_object.node_y_coord %>
</p>

<p>
  <b>Node x pr coord:</b>
  <%= @spin_object.node_x_pr_coord %>
</p>

<p>
  <b>Node type:</b>
  <%= @spin_object.node_type %>
</p>

<p>
  <b>Node version:</b>
  <%= @spin_object.node_version %>
</p>

<p>
  <b>Object name:</b>
  <%= @spin_object.object_name %>
</p>

<p>
  <b>Object attributes:</b>
  <%= @spin_object.object_attributes %>
</p>

<p>
  <b>Src platform:</b>
  <%= @spin_object.src_platform %>
</p>

<p>
  <b>Src attributes:</b>
  <%= @spin_object.src_attributes %>
</p>

<p>
  <b>Date created:</b>
  <%= @spin_object.date_created %>
</p>

<p>
  <b>Date modified:</b>
  <%= @spin_object.date_modified %>
</p>


<%= link_to 'Edit', edit_spin_object_path(@spin_object) %> |
<%= link_to 'Back', spin_objects_path %>