config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :spin_vfs_storage_mappings

  resources :spin_vfs_tree_mappings

  resources :spin_virtual_file_systems

  resources :user_interface_managers

  resources :spin_user_attributes

  resources :secrfet_files_login

  resources :spin_objects

  resources :spin_storages

  resources :spin_domains

  resources :spin_sessions

  resources :spin_group_members

  resources :spin_users

  resources :spin_groups

  resources :target_folder_data

  resources :sender_data

  resources :search_option_data

  resources :search_condition_data

  resources :recycler_data

  resources :operator_data

  resources :member_data

  resources :group_data

  resources :folder_data

  resources :file_data

  resources :domain_data

  resources :secret_files_sessions

  get 'hello_world', to: 'hello_world#index'

  get 'secret_files_login/login.tdx'  => 'secret_files_login#proc_login'
  match 'secret_files/login.tdx'  => 'secret_files_login#proc_login', :via => [:get, :post]
  get 'secret_files_login/activation.php'  => 'secret_files_login#proc_activation'
  get 'secret_files_login/auth.html'  => 'secret_files_login#proc_secret_files_login_view'
  get 'secret_files_login'  => 'secret_files_login#proc_secret_files_login_view'
  match 'secret_files_login/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  match 'secret_files/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  get 'secret_files/uploader/upload_proc' => 'uploader#upload_proc'
  get 'secret_files/downloader/download_proc' => 'downloader#download_proc'
  get 'secret_files/secret_files/spin_api_request' => 'fsmanager#spin_api_request_proc'
  get 'secret_files/secret_files/multipart_form' => 'uploader#filemanager_upload_request'
  post 'secret_files_login/login.tdx'  => 'secret_files_login#proc_login'
  post 'secret_files_login/activation.php'  => 'secret_files_login#proc_activation'
  post 'secret_files_login/auth.html'  => 'secret_files_login#proc_secret_files_login_view'
  post 'secret_files_login'  => 'secret_files_login#proc_secret_files_login_view'
  match 'secret_files_login/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  match 'secret_files/tdx/updatedata.tdx' => 'secret_files#php', :via => [:get, :post]
  post 'secret_files/uploader/upload_proc' => 'uploader#upload_proc'
  post 'secret_files/downloader/download_proc' => 'downloader#download_proc'
  post 'secret_files/secret_files/spin_api_request' => 'fsmanager#spin_api_request_proc'
  post 'secret_files/secret_files/multipart_form' => 'uploader#filemanager_upload_request'
  get 'secret_files_ipad/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_ipad/tdx/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_ipad/tdx/updatedata.tdx' => 'secret_files#php'
  get 'secret_files_ipad'  => 'secret_files_login#proc_secret_files_ipad_login_view'
  get 'secret_files_ipad/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_ipad/tdx/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_ipad/index.html' => 'secret_files#proc_login_view'
  get 'secret_files_iphone/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_iphone/tdx/login.tdx'  => 'secret_files_login#proc_mobile_login'
  get 'secret_files_iphone/tdx/updatedata.tdx' => 'secret_files#php'
  get 'secret_files_iphone'  => 'secret_files_login#proc_secret_files_ipad_login_view'
  get 'secret_files_iphone/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_iphone/tdx/index.tdx' => 'secret_files#proc_login_view'
  get 'secret_files_iphone/index.html' => 'secret_files#proc_login_view'
  get 'secret_files/spin_api_request' => 'spin_api#request_broker'
  post 'secret_files/spin_api_request' => 'spin_api#request_broker'
  get 'm2a/index.tdx' => 'spin_m2a#proc_login_view'
  get 'm2a/index.html' => 'spin_m2a#proc_login_view'
  get 'secret_files/spin/domainsA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/domainsB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersAT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersBT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersATFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/foldersBTFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/file_listA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/file_listB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/file_listS.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/recycler.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/search_option.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/search_conditions.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_tree.sfl' => 'filer_display#proc_display_view'
  get 'secret_files/spin/group_list_all.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_folder.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_file.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_created.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/member_list_mygroup.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/mail_senders.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/working_files.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/active_operator.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/group_list_created.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/user_list.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  get 'secret_files/spin/select_list.sfl' => 'filer_display#proc_display_view'

  get 'secret_files/spin/clipboards.sfl' => 'filer_display#proc_display_view' # => domain name and attributes

  get 'secret_files/spin/ArchivedData.sfl' => 'filer_display#proc_display_view' #アーカイブ解除
  get 'secret_files/spin/SyncedData.sfl' => 'filer_display#proc_display_view' #同期解除
  get 'secret_files/spin/dlfolders.sfl' => 'filer_display#proc_display_view' #ダウンロード
  get 'secret_files/spin/dlfiles.sfl' => 'filer_display#proc_display_view' #ダウンロード

  post 'secret_files/spin/domainsA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/domainsB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersAT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersBT.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersATFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/foldersBTFi.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/file_listA.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/file_listB.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/file_listS.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/recycler.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/search_option.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/search_conditions.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_tree.sfl' => 'filer_display#proc_display_view'
  post 'secret_files/spin/group_list_all.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_folder.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_file.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/group_list_created.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/member_list_mygroup.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/mail_senders.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/working_files.sfl' => 'filer_display#proc_display_view' # => domain name and attributes
  post 'secret_files/spin/active_operator.sfl' => 'filer_display#proc_display_view' # => domain name and attributes

app/controllers/folder_data_controller.rb
class FolderDataController < ApplicationController
  # GET /folder_data
  # GET /folder_data.json
  def index
    @folder_data = FolderDatum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @folder_data }
    end
  end

  # GET /folder_data/1
  # GET /folder_data/1.json
  def show
    @folder_datum = FolderDatum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @folder_datum }
    end
  end

  # GET /folder_data/new
  # GET /folder_data/new.json
  def new
    @folder_datum = FolderDatum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @folder_datum }
    end
  end

  # GET /folder_data/1/edit
  def edit
    @folder_datum = FolderDatum.find(params[:id])
  end

  # POST /folder_data
  # POST /folder_data.json
  def create
    @folder_datum = FolderDatum.new(params[:folder_datum])

    respond_to do |format|
      if @folder_datum.save
        format.html { redirect_to @folder_datum, :notice => 'Folder datum was successfully created.' }
        format.json { render :json => @folder_datum, :status => :created, :location => @folder_datum }
      else
        format.html { render :action => "new" }
        format.json { render :json => @folder_datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /folder_data/1
  # PUT /folder_data/1.json
  def update
    @folder_datum = FolderDatum.find(params[:id])

    respond_to do |format|
      if @folder_datum.update_attributes(params[:folder_datum])
        format.html { redirect_to @folder_datum, :notice => 'Folder datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @folder_datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /folder_data/1
  # DELETE /folder_data/1.json
  def destroy
    @folder_datum = FolderDatum.find(params[:id])
    @folder_datum.destroy

    respond_to do |format|
      format.html { redirect_to folder_data_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/folder_data_helper.rb
module FolderDataHelper
end

app/views/folder_data/_form.html.erb
<%= form_for(@folder_datum) do |f| %>
  <% if @folder_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder_datum.errors.count, "error") %> prohibited this folder_datum from being saved:</h2>

      <ul>
      <% @folder_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :session_id %><br />
    <%= f.text_field :session_id %>
  </div>
  <div class="field">
    <%= f.label :hash_key %><br />
    <%= f.text_field :hash_key %>
  </div>
  <div class="field">
    <%= f.label :cont_location %><br />
    <%= f.text_field :cont_location %>
  </div>
  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :img %><br />
    <%= f.text_field :img %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :folder_name %><br />
    <%= f.text_field :folder_name %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :ownership %><br />
    <%= f.text_field :ownership %>
  </div>
  <div class="field">
    <%= f.label :control_right %><br />
    <%= f.text_field :control_right %>
  </div>
  <div class="field">
    <%= f.label :parent_readable_status %><br />
    <%= f.text_field :parent_readable_status %>
  </div>
  <div class="field">
    <%= f.label :parent_writable_status %><br />
    <%= f.text_field :parent_writable_status %>
  </div>
  <div class="field">
    <%= f.label :folder_readable_status %><br />
    <%= f.text_field :folder_readable_status %>
  </div>
  <div class="field">
    <%= f.label :folder_writable_status %><br />
    <%= f.text_field :folder_writable_status %>
  </div>
  <div class="field">
    <%= f.label :workingFolder %><br />
    <%= f.text_field :workingFolder %>
  </div>
  <div class="field">
    <%= f.label :subFolders %><br />
    <%= f.number_field :subFolders %>
  </div>
  <div class="field">
    <%= f.label :fileNumber %><br />
    <%= f.number_field :fileNumber %>
  </div>
  <div class="field">
    <%= f.label :creator %><br />
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :created_date %><br />
    <%= f.date_select :created_date %>
  </div>
  <div class="field">
    <%= f.label :updater %><br />
    <%= f.text_field :updater %>
  </div>
  <div class="field">
    <%= f.label :updated_date %><br />
    <%= f.date_select :updated_date %>
  </div>
  <div class="field">
    <%= f.label :usedSpace %><br />
    <%= f.number_field :usedSpace %>
  </div>
  <div class="field">
    <%= f.label :restSpace %><br />
    <%= f.number_field :restSpace %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :usedRate %><br />
    <%= f.number_field :usedRate %>
  </div>
  <div class="field">
    <%= f.label :cls %><br />
    <%= f.text_field :cls %>
  </div>
  <div class="field">
    <%= f.label :expanded %><br />
    <%= f.check_box :expanded %>
  </div>
  <div class="field">
    <%= f.label :leaf %><br />
    <%= f.check_box :leaf %>
  </div>
  <div class="field">
    <%= f.label :children %><br />
    <%= f.text_field :children %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folder_data/edit.html.erb
<h1>Editing folder_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder_datum %> |
<%= link_to 'Back', folder_data_path %>

app/views/folder_data/index.html.erb
<h1>Listing folder_data</h1>

<table>
  <tr>
    <th>Session</th>
    <th>Hash key</th>
    <th>Cont location</th>
    <th>Id</th>
    <th>Img</th>
    <th>Text</th>
    <th>Folder name</th>
    <th>Owner</th>
    <th>Ownership</th>
    <th>Control right</th>
    <th>Parent readable status</th>
    <th>Parent writable status</th>
    <th>Folder readable status</th>
    <th>Folder writable status</th>
    <th>Workingfolder</th>
    <th>Subfolders</th>
    <th>Filenumber</th>
    <th>Creator</th>
    <th>Created date</th>
    <th>Updater</th>
    <th>Updated date</th>
    <th>Usedspace</th>
    <th>Restspace</th>
    <th>Capacity</th>
    <th>Usedrate</th>
    <th>Cls</th>
    <th>Expanded</th>
    <th>Leaf</th>
    <th>Children</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @folder_data.each do |folder_datum| %>
  <tr>
    <td><%= folder_datum.session_id %></td>
    <td><%= folder_datum.hash_key %></td>
    <td><%= folder_datum.cont_location %></td>
    <td><%= folder_datum.id %></td>
    <td><%= folder_datum.img %></td>
    <td><%= folder_datum.text %></td>
    <td><%= folder_datum.folder_name %></td>
    <td><%= folder_datum.owner %></td>
    <td><%= folder_datum.ownership %></td>
    <td><%= folder_datum.control_right %></td>
    <td><%= folder_datum.parent_readable_status %></td>
    <td><%= folder_datum.parent_writable_status %></td>
    <td><%= folder_datum.folder_readable_status %></td>
    <td><%= folder_datum.folder_writable_status %></td>
    <td><%= folder_datum.workingFolder %></td>
    <td><%= folder_datum.subFolders %></td>
    <td><%= folder_datum.fileNumber %></td>
    <td><%= folder_datum.creator %></td>
    <td><%= folder_datum.created_date %></td>
    <td><%= folder_datum.updater %></td>
    <td><%= folder_datum.updated_date %></td>
    <td><%= folder_datum.usedSpace %></td>
    <td><%= folder_datum.restSpace %></td>
    <td><%= folder_datum.capacity %></td>
    <td><%= folder_datum.usedRate %></td>
    <td><%= folder_datum.cls %></td>
    <td><%= folder_datum.expanded %></td>
    <td><%= folder_datum.leaf %></td>
    <td><%= folder_datum.children %></td>
    <td><%= link_to 'Show', folder_datum %></td>
    <td><%= link_to 'Edit', edit_folder_datum_path(folder_datum) %></td>
    <td><%= link_to 'Destroy', folder_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Folder datum', new_folder_datum_path %>

app/views/folder_data/new.html.erb
<h1>New folder_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', folder_data_path %>

app/views/folder_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Session:</b>
  <%= @folder_datum.session_id %>
</p>

<p>
  <b>Hash key:</b>
  <%= @folder_datum.hash_key %>
</p>

<p>
  <b>Cont location:</b>
  <%= @folder_datum.cont_location %>
</p>

<p>
  <b>Id:</b>
  <%= @folder_datum.id %>
</p>

<p>
  <b>Img:</b>
  <%= @folder_datum.img %>
</p>

<p>
  <b>Text:</b>
  <%= @folder_datum.text %>
</p>

<p>
  <b>Folder name:</b>
  <%= @folder_datum.folder_name %>
</p>

<p>
  <b>Owner:</b>
  <%= @folder_datum.owner %>
</p>

<p>
  <b>Ownership:</b>
  <%= @folder_datum.ownership %>
</p>

<p>
  <b>Control right:</b>
  <%= @folder_datum.control_right %>
</p>

<p>
  <b>Parent readable status:</b>
  <%= @folder_datum.parent_readable_status %>
</p>

<p>
  <b>Parent writable status:</b>
  <%= @folder_datum.parent_writable_status %>
</p>

<p>
  <b>Folder readable status:</b>
  <%= @folder_datum.folder_readable_status %>
</p>

<p>
  <b>Folder writable status:</b>
  <%= @folder_datum.folder_writable_status %>
</p>

<p>
  <b>Workingfolder:</b>
  <%= @folder_datum.workingFolder %>
</p>

<p>
  <b>Subfolders:</b>
  <%= @folder_datum.subFolders %>
</p>

<p>
  <b>Filenumber:</b>
  <%= @folder_datum.fileNumber %>
</p>

<p>
  <b>Creator:</b>
  <%= @folder_datum.creator %>
</p>

<p>
  <b>Created date:</b>
  <%= @folder_datum.created_date %>
</p>

<p>
  <b>Updater:</b>
  <%= @folder_datum.updater %>
</p>

<p>
  <b>Updated date:</b>
  <%= @folder_datum.updated_date %>
</p>

<p>
  <b>Usedspace:</b>
  <%= @folder_datum.usedSpace %>
</p>

<p>
  <b>Restspace:</b>
  <%= @folder_datum.restSpace %>
</p>

<p>
  <b>Capacity:</b>
  <%= @folder_datum.capacity %>
</p>

<p>
  <b>Usedrate:</b>
  <%= @folder_datum.usedRate %>
</p>

<p>
  <b>Cls:</b>
  <%= @folder_datum.cls %>
</p>

<p>
  <b>Expanded:</b>
  <%= @folder_datum.expanded %>
</p>

<p>
  <b>Leaf:</b>
  <%= @folder_datum.leaf %>
</p>

<p>
  <b>Children:</b>
  <%= @folder_datum.children %>
</p>


<%= link_to 'Edit', edit_folder_datum_path(@folder_datum) %> |
<%= link_to 'Back', folder_data_path %>